version: '3'
services:
 db:
   image: mysql   
   volumes:
    - .:/docker-entrypoint-initdb.d
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: insta_admin
    MYSQL_PASSWORD: insta2018
    MYSQL_DATABASE: RSVP
   networks:
    - rsvpnet
   

 web:
   build: . 
   ports:
           - "5000:5000"
   environment:
    TEXT1: Hackfest 
    TEXT2: Registration 
    ORGANIZER: UVCE
   depends_on:
    - db
   networks:
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
